version: '3.4'

services:
  japanprefecturescitiesapi:
    image: japanprefecturescitiesapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - data_volume:/var/lib/data


volumes:
  data_volume:
    driver: local