japan_facts = [
    "In Japanese, the name “Japan” is Nihon or Nippon, which means “Land of the Rising Sun.” It was once believed that Japan was the first country to see the sun rise in the East in the morning",
    "Japan has the third longest life expectancy in the world with men living to 81 years old and women living to almost 88 years old",
    "Japan consists of over 6,800 islands",
    "Home to 33 million people, the Tokyo-Yokohama metropolitan area is the largest populated metropolitan region in the world",
    "Japan has more than 3,000 McDonald’s restaurants, the largest number in any country outside the U.S",
    "69% of Japan is Covered in Forest",
    "70% of Japan is mountainous – including over 100 active volcanoes",
    "There are More than 1,500 Earthquakes a Year!",
    "The 1923 Kanto Earthquake was the Country’s Deadliest Earthquake",
    "Japan has the World’s Deepest Underwater Postbox",
    "Mount Fuji is a Sacred Place",
    "Japanese have a Deep Affection to Nature",
    "The Sea of Japan Holds an Abundance of Fish",
    "The Portuguese were the First Europeans to Visit Japan",
    "Japan had a Period of Complete Isolation from the Rest of the World",
    "Japanese Trains are Extremely Punctual",
    "The Oldest Onsen (Hot Spring) is 3,000 Years Old",
    "Only 1.7% of Land in Japan is Pastures and Grassland",
    "Only 12.7% of the Land in Japan is Okay for Agriculture",
    "Japan has one of the Lowest Unemployment Rates in the World",
    "Japan Just Legalized Gambling Casinos",
    "Japan Birth Rate is Lowest it’s Ever Been",
    "Slurping Noodles in Japan is a Sign of Appreciation",
    "Japan is one of the Safest Countries in the World",
    "In Japan there are no Shoes Allowed Inside",
    "There are Musical Toilets in Japan",
    "The Number 4 is Unlucky in Japan",
    "In Japan Black Cats are a Good Luck Charm",
    "Kids Get Taught How to Clean in School",
    "The Shortest Poetry in the World was Created in Japan and it is called Haiku",
    "Japan has Highest Number of Nobel Laureates In An Asian Country for Physics",
    "Japan is 3rd Biggest Producer of Cars in the World",
    "Japan has an Island of Rabbits (Okunoshima Island)",
    "The Shortest Escalator in the World (5 steps)",
    "Japan has the Busiest Train Station in the World (Shinjuku station 3.6 million people daily)",
    "The World’s First Novel Was Written Here (The Tale of Genji)",
    "Japan has been inhabited since 30,000 B.C.",
    "Japan imports 85% of Jamaica's annual coffee production",
    "Tokyo has the world's largest fish market, handling over 2000 tonnes of marine products daily.",
    "The traditional Christmas Eve meal is KFC",
    "In Japan there are ‘Maid Cafes’ where waitresses dressed in maid costumes act as servants, and treat customers as masters (and mistresses) in a private home, rather than as café patrons",
    "Animated Japanese films and television shows (i.e.: Anime) account for 60% of the world’s animation-based entertainment. So successful is animation in Japan, that there are almost 130 voice-acting schools in the country",
    "Around 24 billion pairs of chopsticks are used in Japan each year",
    "They use more paper for comics than for toilet paper in Japan",
    "Sometimes the trains in Japan are so crowded railway staff are employed to cram passengers inside",
    "Ovens are not nearly as commonplace as rice cookers in Japanese households",
    "There is almost no immigration in Japan. The population is 98% ethnic Japanese",
    "It’s considered inappropriate to blow your nose in public",
    "Japanese sake is made from fermented rice",
    "The fortune cookie dates back to the 19th century and was first made in Kyoto, Japan",
    "日本は島国で、4つの主要な島から成り立っています。",
    "東京は日本の首都であり、最も人口の多い都市です。",
    "富士山は日本で最も高い山であり、国の象徴の一つです。",
    "日本は「太平洋のリング・オブ・ファイア」に位置しており、地震や火山活動が頻繁に発生します。",
    "日本の伝統的な衣装は着物です。",
    "お茶道や華道など、日本には多くの伝統的な芸術や文化があります。",
    "日本語は国の公用語であり、独自の文字であるひらがな、カタカナ、漢字が使われています。",
    "お正月は日本の最も重要な休日であり、1月1日に家族で祝われます。",
    "日本の通貨は円です。",
    "電車は日本で主要な交通手段であり、効率的かつ正確です。",
    "日本の伝統的な音楽楽器には尺八や三味線があります。",
    "日本は新しい技術の先進国であり、多くのテクノロジー企業が存在します。",
    "日本の食文化は世界的に有名で、寿司、刺身、ラーメンなどがあります。",
    "日本は四季がはっきりしており、桜の花見は春の風物詩となっています。",
    "日本は島国で、4つの主要な島から成り立っています。",
    "東京は日本の首都であり、最も人口の多い都市です。",
    "富士山は日本で最も高い山であり、国の象徴の一つです。",
    "日本は「太平洋のリング・オブ・ファイア」に位置しており、地震や火山活動が頻繁に発生します。",
    "日本の伝統的な衣装は着物です。",
    "お茶道や華道など、日本には多くの伝統的な芸術や文化があります。",
    "日本語は国の公用語であり、独自の文字であるひらがな、カタカナ、漢字が使われています。",
    "お正月は日本の最も重要な休日であり、1月1日に家族で祝われます。",
    "日本の通貨は円です。",
    "電車は日本で主要な交通手段であり、効率的かつ正確です。",
    "日本の伝統的な音楽楽器には尺八や三味線があります。",
    "日本は新しい技術の先進国であり、多くのテクノロジー企業が存在します。",
    "日本の食文化は世界的に有名で、寿司、刺身、ラーメンなどがあります。",
    "日本は四季がはっきりしており、桜の花見は春の風物詩となっています。",
    "雪国である北海道では、冬にはスキーや雪祭りがあります。",
    "日本の伝統的な建築物には寺院や城があり、美しい庭園も多く存在します。",
    "アニメやマンガは日本発祥であり、国内外で広く愛されています。",
    "日本の教育制度は厳格であり、制服が一般的な学生服として使われます。",
    "日本のビジネス文化では、名刺交換が一般的であり、相手を尊重する重要な儀式とされています。",
    "日本は世界で最も長寿な国の一つであり、健康食や運動が重視されています。",
    "日本の伝統的な舞踏には能や狂言があり、歌舞伎も有名です。",
    "日本の地域ごとに独自の方言があり、標準語としての日本語以外にも多くのバリエーションが存在します。",
    "日本は多くの祭りで知られており、夏には盆踊りや花火大会が行われます。",
    "日本の自然は美しく、国内には多くの国立公園や自然保護区があります。",
    "日本の伝統的な工芸品には陶芸や木工、漆器などがあります。",
    "日本の政府は天皇制を採用しており、天皇は象徴的存在です。",
    "日本の企業文化では、終身雇用が一般的であり、忠誠心が重要視されます。",
    "日本は世界的な車メーカーとして知られ、トヨタやホンダなどが国内外で成功しています。",
    "日本の温泉は有名であり、地熱活動によって多くの温泉地が存在します。",
    "日本の神社や寺院では、参拝やお賽銭が一般的な宗教活動です。",
    "日本の政府は防衛軍を持っておらず、平和憲法を採用しています。",
    "日本のビジネスマナーでは、会議や取引において正確さと礼儀正しさが求められます。",
    "日本の電子機器産業は世界的に有名であり、ソニーやパナソニックなどが国際的に成功しています。",
    "日本の新幹線は高速鉄道として知られ、快適でスピーディーな移動手段として利用されています。",
    "日本は海の幸と山の幸が豊富であり、食材の新鮮さが重要視されています。",
    "日本の都市部では、高層ビルやモダンなショッピングモールが多く見られます。",
    "日本の敬語は複雑であり、社会的な階層によって使い分けがされます。",
    "日本の大学は国際的に評価され、東京大学などは世界トップの大学として知られています。",
    "日本の祭りや伝統行事では、豪華な衣装や仮面が使われ、迫力のあるパレードが行われます。",
    "日本の地震対策は進んでおり、多くの建物は地震に強化されています。",
    "日本の宗教は神道や仏教が主流であり"
]